---
- id: check-poetry
  name: Poetry check
  description: Validates the structure of the pyproject.toml file
  entry: poetry check
  language: system
  pass_filenames: false
  files: pyproject.toml
- id: export-poetry
  name: Poetry export
  description: Exports pyproject.toml to requirements.txt
  entry: poetry export -f requirements.txt -o requirements.txt
  language: system
  pass_filenames: false
  files: pyproject.toml
